### ISSUE TITLE
I cant find .losses code

### ISSUE THREAD

**Issue by jaekyeongg** [XDUWQ/SketchKnitter#1]
When I checked code, I couldn't find  .losses.
Please let me know detail.
gaussian_diffusion.py line 8 :
from .losses import normal_kl, discretized_gaussian_log_likelihood ()

**Comment by wangqiang9** [comment]
> When I checked code, I couldn't find .losses. Please let me know detail. gaussian_diffusion.py line 8 : from .losses import normal_kl, discretized_gaussian_log_likelihood ()

https://github.com/XDUWQ/SketchKnitter/blob/main/sketch_diffusion/losses.py
