### ISSUE TITLE
Question of N

### ISSUE THREAD

**Issue by ChaoShuoZhang** [XDUWQ/SketchKnitter#15]
When I set N to a smaller number, I ran into the following problem

> ValueError: could not broadcast input array from shape (59,3) into shape (24,3)’

I tried to use my modified code and the result was very bad
`len_seq = min(self.Nmax, self.sketches_normed[idx].shape[0])`
`step = self.sketches_normed[idx].shape[0] // len_seq + 1`
`sampledata = self.sketches_normed[idx][::step]`
`sketch[:len(sampledata), :] = sampledata`
I see that your paper mentions data about N=24, how did you achieve it？

**Comment by ChaoShuoZhang** [comment]
When a sequence is longer than N, how is it handled？

**Comment by wangqiang9** [comment]
It is necessary to truncate the data during data preprocessing, and detailed methods are described in the paper and supplementary materials.
