### ISSUE TITLE
cant not use ddim sample loop function

### ISSUE THREAD

**Issue by jaekyeongg** [XDUWQ/SketchKnitter#3]
TypeError: ddim_sample_loop() missing 3 required positional arguments: 'data', 'raster', and 'loss'
I used below samping command.
python sample.py  --model_path ./log/ema_0.9999_050000.pt --pen_break 0.1 --save_path ./ --use_ddim True --log_dir ./log/ --diffusion_steps 100 --noise_schedule linear --image_size 96 --num_channels 96 --num_res_blocks 3

**Comment by wangqiang9** [comment]
> TypeError: ddim_sample_loop() missing 3 required positional arguments: 'data', 'raster', and 'loss' I used below samping command. python sample.py --model_path ./log/ema_0.9999_050000.pt --pen_break 0.1 --save_path ./ --use_ddim True --log_dir ./log/ --diffusion_steps 100 --noise_schedule linear --image_size 96 --num_channels 96 --num_res_blocks 3

This is a duplicate issue, please refer to this discussion https://github.com/XDUWQ/SketchKnitter/issues/4
