### ISSUE TITLE
evaluator

### ISSUE THREAD

**Issue by dngu7** [XDUWQ/SketchKnitter#5]
The evaluator needs some instructions on how to use it.

I'm testing the evaluator but the `read_activations` function does not accept the reference dataset. 
`python evaluations/evaluator.py datasets/airplane.npz datasets/airplane.npz`

The above command throws the below error:
`ValueError: missing arr_0 in npz file`

Can you also advise on the right format for samples? Its not very clear from the code.

**Comment by dngu7** [comment]
Also. the sample.py does not save any samples anywhere. 
```
sample_all = bin_pen(sample_all, args.pen_break)
print(f"sample all {sample_all} is saved!")
```
This code seems to be printing the whole vector ?

**Comment by wangqiang9** [comment]
Please use the correct method to read and use npz files. If you are not familiar with the relevant methods, please learn the relevant APIs yourself, such as: https://numpy.org/doc/stable/reference/generated/numpy.savez.html、
https://numpy.org/doc/stable/reference/generated/numpy.savez_compressed.html

**Comment by wangqiang9** [comment]
> The evaluator needs some instructions on how to use it.

Here are the ways to use scripts for your reference: https://github.com/XDUWQ/SketchKnitter#evaluation

**Comment by dngu7** [comment]
I am following the script from your readme file, however that exact script creates the error I mentioned earlier. 

Are you suggesting that I need to load and savez the dataset before calling **python evaluations/evaluator.py  [/path/to/reference-data] ** 

I assumed from your script that the [/path/to/reference-data] argument would accept the dataset automatically. 

Can you please re-open this issue?
