### ISSUE TITLE
Some questions about samples

### ISSUE THREAD

**Issue by ydyhello** [XDUWQ/SketchKnitter#7]
Thank you very much for the code, I have some questions I would like to ask.
The sample.py does not save any samples anywhere.

```
sample_all = bin_pen(sample_all, args.pen_break)
print(f"sample all {sample_all} is saved!")
```
This code seems to be printing the whole vector ?

**Comment by wangqiang9** [comment]
sorry, the print message is not very accurate, I have modified the comments and code in this section. Thank you for your feedback.

**Comment by ydyhello** [comment]
> sorry, the print message is not very accurate, I have modified the comments and code in this section. Thank you for your feedback.

Thank you so much for your work!

**Comment by ydyhello** [comment]
> sorry, the print message is not very accurate, I have modified the comments and code in this section. Thank you for your feedback.
```
        sample_all = th.cat((sample, pen_state), 2).cpu()
        sample_all = bin_pen(sample_all, args.pen_break)
```
How to save sample_all in .npz format, I didn't find it in your code.

**Comment by dngu7** [comment]
Second this. Because of this, there is no way to evaluate or benchmark the paper's results.

**Comment by LizzyEw** [comment]
Same question here. How can we save "sample_all" to get a result ?
