### ISSUE TITLE
Question about draw_sketch.py

### ISSUE THREAD

**Issue by LizzyEw** [XDUWQ/SketchKnitter#9]
Hi there! 
Firstly, thank you for your advice about sample_all in sample.py! However, I noticed that in your dataset such as moon.npz, the size of data.train (as shown in the 80th line in draw_sketch.py) is 70000×3. While the size I get in sample_all.npz (from the 73rd line in sample.py) is 16×96×4. 
So could you please explain how you save sample_all into the true npz file? I've tried 
`np.savez(args.save_path + "sample0.npz", train=sample_all)` but it didn't work when draw_sketch.
Thank you for your help agian!

**Comment by wangqiang9** [comment]
Hi，The right saved sizes `Batch_size, image_size, 3`. So I think may be there are error of you saving code.
I have updated the code for saving npz files in the latest code: https://github.com/XDUWQ/SketchKnitter/blob/8a44cf138acba2c406d71bd0350b94ed755ad26c/sample.py#L74
